import { State } from '@/types';

export interface StateInfo extends State {
  chief_minister: string;
  cm_party: string;
  cm_party_color: string;
  cm_photo?: string;
  landmark: string;
  landmark_emoji: string;
  landmark_desc: string;
  ruling_party: string;
  formed_year: number;
  districts_count: number;
  is_ut: boolean;
}

export const INDIA_STATES: StateInfo[] = [
  {
    id: 'AP', name: 'Andhra Pradesh', capital: 'Amaravati',
    capital_lat: 16.5193, capital_lng: 80.5161,
    geojson_id: 'Andhra Pradesh',
    chief_minister: 'N. Chandrababu Naidu', cm_party: 'Telugu Desam Party', cm_party_color: '#FFDE00',
    landmark: 'Tirupati Balaji Temple', landmark_emoji: '🛕',
    landmark_desc: 'The richest temple in the world, visited by 50,000–100,000 pilgrims daily',
    ruling_party: 'TDP', formed_year: 1956, districts_count: 26, is_ut: false,
  },
  {
    id: 'AR', name: 'Arunachal Pradesh', capital: 'Itanagar',
    capital_lat: 27.0844, capital_lng: 93.6053,
    geojson_id: 'Arunachal Pradesh',
    chief_minister: 'Pema Khandu', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Tawang Monastery', landmark_emoji: '⛩️',
    landmark_desc: 'The largest monastery in India and second largest in the world',
    ruling_party: 'BJP', formed_year: 1987, districts_count: 26, is_ut: false,
  },
  {
    id: 'AS', name: 'Assam', capital: 'Dispur',
    capital_lat: 26.1445, capital_lng: 91.7362,
    geojson_id: 'Assam',
    chief_minister: 'Himanta Biswa Sarma', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Kamakhya Temple', landmark_emoji: '🛕',
    landmark_desc: 'One of the 51 Shakti Peethas, perched on Nilachal Hill overlooking Guwahati',
    ruling_party: 'BJP', formed_year: 1912, districts_count: 35, is_ut: false,
  },
  {
    id: 'BR', name: 'Bihar', capital: 'Patna',
    capital_lat: 25.5941, capital_lng: 85.1376,
    geojson_id: 'Bihar',
    chief_minister: 'Nitish Kumar', cm_party: 'Janata Dal (United)', cm_party_color: '#005B96',
    landmark: 'Mahabodhi Temple', landmark_emoji: '🏛️',
    landmark_desc: 'UNESCO World Heritage Site — where Buddha attained enlightenment in Bodh Gaya',
    ruling_party: 'JDU+BJP', formed_year: 1912, districts_count: 38, is_ut: false,
  },
  {
    id: 'CG', name: 'Chhattisgarh', capital: 'Raipur',
    capital_lat: 21.2514, capital_lng: 81.6296,
    geojson_id: 'Chhattisgarh',
    chief_minister: 'Vishnu Deo Sai', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Chitrakote Falls', landmark_emoji: '🌊',
    landmark_desc: 'Widest waterfall in India — known as the Niagara of India',
    ruling_party: 'BJP', formed_year: 2000, districts_count: 33, is_ut: false,
  },
  {
    id: 'GA', name: 'Goa', capital: 'Panaji',
    capital_lat: 15.4909, capital_lng: 73.8278,
    geojson_id: 'Goa',
    chief_minister: 'Pramod Sawant', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Basilica of Bom Jesus', landmark_emoji: '⛪',
    landmark_desc: 'UNESCO World Heritage Site holding the mortal remains of St. Francis Xavier',
    ruling_party: 'BJP', formed_year: 1987, districts_count: 2, is_ut: false,
  },
  {
    id: 'GJ', name: 'Gujarat', capital: 'Gandhinagar',
    capital_lat: 23.2156, capital_lng: 72.6369,
    geojson_id: 'Gujarat',
    chief_minister: 'Bhupendra Patel', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Statue of Unity', landmark_emoji: '🗽',
    landmark_desc: 'World\'s tallest statue at 182m — dedicated to Sardar Vallabhbhai Patel',
    ruling_party: 'BJP', formed_year: 1960, districts_count: 33, is_ut: false,
  },
  {
    id: 'HR', name: 'Haryana', capital: 'Chandigarh',
    capital_lat: 30.7333, capital_lng: 76.7794,
    geojson_id: 'Haryana',
    chief_minister: 'Nayab Singh Saini', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Kurukshetra', landmark_emoji: '🏛️',
    landmark_desc: 'Sacred site of the Mahabharata war — Brahma Sarovar is Asia\'s largest sacred tank',
    ruling_party: 'BJP', formed_year: 1966, districts_count: 22, is_ut: false,
  },
  {
    id: 'HP', name: 'Himachal Pradesh', capital: 'Shimla',
    capital_lat: 31.1048, capital_lng: 77.1734,
    geojson_id: 'Himachal Pradesh',
    chief_minister: 'Sukhvinder Singh Sukhu', cm_party: 'Indian National Congress', cm_party_color: '#19AAED',
    landmark: 'Rohtang Pass', landmark_emoji: '🏔️',
    landmark_desc: 'Gateway to Lahaul-Spiti valley, 3,978m high Himalayan mountain pass',
    ruling_party: 'INC', formed_year: 1971, districts_count: 12, is_ut: false,
  },
  {
    id: 'JH', name: 'Jharkhand', capital: 'Ranchi',
    capital_lat: 23.3441, capital_lng: 85.3096,
    geojson_id: 'Jharkhand',
    chief_minister: 'Hemant Soren', cm_party: 'Jharkhand Mukti Morcha', cm_party_color: '#1B7F4F',
    landmark: 'Hundru Falls', landmark_emoji: '🌊',
    landmark_desc: 'Highest waterfall in Jharkhand on the Subarnarekha river, 98m tall',
    ruling_party: 'JMM', formed_year: 2000, districts_count: 24, is_ut: false,
  },
  {
    id: 'KA', name: 'Karnataka', capital: 'Bengaluru',
    capital_lat: 12.9716, capital_lng: 77.5946,
    geojson_id: 'Karnataka',
    chief_minister: 'Siddaramaiah', cm_party: 'Indian National Congress', cm_party_color: '#19AAED',
    landmark: 'Vidhana Soudha', landmark_emoji: '🏛️',
    landmark_desc: 'Seat of the State Legislature — one of the largest legislative buildings in India',
    ruling_party: 'INC', formed_year: 1956, districts_count: 31, is_ut: false,
  },
  {
    id: 'KL', name: 'Kerala', capital: 'Thiruvananthapuram',
    capital_lat: 8.5241, capital_lng: 76.9366,
    geojson_id: 'Kerala',
    chief_minister: 'Pinarayi Vijayan', cm_party: 'CPI(M)', cm_party_color: '#CC0000',
    landmark: 'Padmanabhaswamy Temple', landmark_emoji: '🛕',
    landmark_desc: 'Wealthiest temple in the world — vaults contain treasures worth ₹1 lakh crore+',
    ruling_party: 'LDF', formed_year: 1956, districts_count: 14, is_ut: false,
  },
  {
    id: 'MP', name: 'Madhya Pradesh', capital: 'Bhopal',
    capital_lat: 23.2599, capital_lng: 77.4126,
    geojson_id: 'Madhya Pradesh',
    chief_minister: 'Mohan Yadav', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Khajuraho Temples', landmark_emoji: '🛕',
    landmark_desc: 'UNESCO World Heritage Site — medieval Hindu & Jain temple complex',
    ruling_party: 'BJP', formed_year: 1956, districts_count: 55, is_ut: false,
  },
  {
    id: 'MH', name: 'Maharashtra', capital: 'Mumbai',
    capital_lat: 19.0760, capital_lng: 72.8777,
    geojson_id: 'Maharashtra',
    chief_minister: 'Devendra Fadnavis', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Gateway of India', landmark_emoji: '🏛️',
    landmark_desc: 'Iconic arch monument built in 1924 on the waterfront of Mumbai',
    ruling_party: 'BJP+SS', formed_year: 1960, districts_count: 36, is_ut: false,
  },
  {
    id: 'MN', name: 'Manipur', capital: 'Imphal',
    capital_lat: 24.8170, capital_lng: 93.9368,
    geojson_id: 'Manipur',
    chief_minister: 'N. Biren Singh', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Loktak Lake', landmark_emoji: '🏞️',
    landmark_desc: 'Largest freshwater lake in Northeast India — famous for floating phumdis',
    ruling_party: 'BJP', formed_year: 1972, districts_count: 16, is_ut: false,
  },
  {
    id: 'ML', name: 'Meghalaya', capital: 'Shillong',
    capital_lat: 25.5788, capital_lng: 91.8933,
    geojson_id: 'Meghalaya',
    chief_minister: 'Conrad Sangma', cm_party: 'National People\'s Party', cm_party_color: '#FF8C00',
    landmark: 'Living Root Bridges', landmark_emoji: '🌿',
    landmark_desc: 'Natural bridges made of living tree roots — centuries old in Cherrapunji',
    ruling_party: 'NPP', formed_year: 1972, districts_count: 12, is_ut: false,
  },
  {
    id: 'MZ', name: 'Mizoram', capital: 'Aizawl',
    capital_lat: 23.7271, capital_lng: 92.7176,
    geojson_id: 'Mizoram',
    chief_minister: 'Lalduhoma', cm_party: 'Zoram People\'s Movement', cm_party_color: '#22c55e',
    landmark: 'Phawngpui Blue Mountain', landmark_emoji: '🏔️',
    landmark_desc: 'Highest peak in Mizoram at 2,157m — called the \'Blue Mountain\'',
    ruling_party: 'ZPM', formed_year: 1987, districts_count: 11, is_ut: false,
  },
  {
    id: 'NL', name: 'Nagaland', capital: 'Kohima',
    capital_lat: 25.6747, capital_lng: 94.1086,
    geojson_id: 'Nagaland',
    chief_minister: 'Neiphiu Rio', cm_party: 'Nationalist Democratic Progressive Party', cm_party_color: '#6366f1',
    landmark: 'Hornbill Festival', landmark_emoji: '🎪',
    landmark_desc: 'Festival of Festivals — 10-day extravaganza of Naga tribal culture every December',
    ruling_party: 'NDPP', formed_year: 1963, districts_count: 16, is_ut: false,
  },
  {
    id: 'OD', name: 'Odisha', capital: 'Bhubaneswar',
    capital_lat: 20.2961, capital_lng: 85.8245,
    geojson_id: 'Orissa',
    chief_minister: 'Mohan Charan Majhi', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Konark Sun Temple', landmark_emoji: '🛕',
    landmark_desc: 'UNESCO World Heritage Site — 13th century Sun Temple shaped like a giant chariot',
    ruling_party: 'BJP', formed_year: 1936, districts_count: 30, is_ut: false,
  },
  {
    id: 'PB', name: 'Punjab', capital: 'Chandigarh',
    capital_lat: 30.7333, capital_lng: 76.7794,
    geojson_id: 'Punjab',
    chief_minister: 'Bhagwant Mann', cm_party: 'Aam Aadmi Party', cm_party_color: '#0066FF',
    landmark: 'Golden Temple', landmark_emoji: '🕌',
    landmark_desc: 'Harmandir Sahib — holiest shrine of Sikhism, feeds 100,000 people daily for free',
    ruling_party: 'AAP', formed_year: 1966, districts_count: 23, is_ut: false,
  },
  {
    id: 'RJ', name: 'Rajasthan', capital: 'Jaipur',
    capital_lat: 26.9124, capital_lng: 75.7873,
    geojson_id: 'Rajasthan',
    chief_minister: 'Bhajanlal Sharma', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Amber Fort', landmark_emoji: '🏯',
    landmark_desc: 'UNESCO World Heritage Site — 16th century hilltop fort overlooking Maota Lake',
    ruling_party: 'BJP', formed_year: 1956, districts_count: 50, is_ut: false,
  },
  {
    id: 'SK', name: 'Sikkim', capital: 'Gangtok',
    capital_lat: 27.3314, capital_lng: 88.6138,
    geojson_id: 'Sikkim',
    chief_minister: 'Prem Singh Tamang', cm_party: 'Sikkim Krantikari Morcha', cm_party_color: '#22d3ee',
    landmark: 'Kanchenjunga', landmark_emoji: '🏔️',
    landmark_desc: 'Third highest mountain in the world at 8,586m — sacred to the Sikkimese people',
    ruling_party: 'SKM', formed_year: 1975, districts_count: 6, is_ut: false,
  },
  {
    id: 'TN', name: 'Tamil Nadu', capital: 'Chennai',
    capital_lat: 13.0827, capital_lng: 80.2707,
    geojson_id: 'Tamil Nadu',
    chief_minister: 'M. K. Stalin', cm_party: 'Dravida Munnetra Kazhagam', cm_party_color: '#CC0000',
    landmark: 'Meenakshi Amman Temple', landmark_emoji: '🛕',
    landmark_desc: 'Madurai temple with 14 gopurams — one of the largest Hindu temples in the world',
    ruling_party: 'DMK', formed_year: 1950, districts_count: 38, is_ut: false,
  },
  {
    id: 'TG', name: 'Telangana', capital: 'Hyderabad',
    capital_lat: 17.3850, capital_lng: 78.4867,
    geojson_id: 'Telangana',
    chief_minister: 'A. Revanth Reddy', cm_party: 'Indian National Congress', cm_party_color: '#19AAED',
    landmark: 'Charminar', landmark_emoji: '🕌',
    landmark_desc: 'Built in 1591 by Muhammad Quli Qutb Shah — icon of Hyderabad and symbol of Telangana',
    ruling_party: 'INC', formed_year: 2014, districts_count: 33, is_ut: false,
  },
  {
    id: 'TR', name: 'Tripura', capital: 'Agartala',
    capital_lat: 23.8315, capital_lng: 91.2868,
    geojson_id: 'Tripura',
    chief_minister: 'Manik Saha', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Ujjayanta Palace', landmark_emoji: '🏰',
    landmark_desc: 'Former royal palace built in 1901 — now a state museum in Agartala',
    ruling_party: 'BJP', formed_year: 1972, districts_count: 8, is_ut: false,
  },
  {
    id: 'UP', name: 'Uttar Pradesh', capital: 'Lucknow',
    capital_lat: 26.8467, capital_lng: 80.9462,
    geojson_id: 'Uttar Pradesh',
    chief_minister: 'Yogi Adityanath', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Taj Mahal', landmark_emoji: '🕌',
    landmark_desc: 'UNESCO World Heritage Site — 17th century ivory-white marble mausoleum in Agra',
    ruling_party: 'BJP', formed_year: 1950, districts_count: 75, is_ut: false,
  },
  {
    id: 'UK', name: 'Uttarakhand', capital: 'Dehradun',
    capital_lat: 30.3165, capital_lng: 78.0322,
    geojson_id: 'Uttaranchal',
    chief_minister: 'Pushkar Singh Dhami', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'Char Dham', landmark_emoji: '🛕',
    landmark_desc: 'Four sacred Hindu pilgrimage sites: Yamunotri, Gangotri, Kedarnath, Badrinath',
    ruling_party: 'BJP', formed_year: 2000, districts_count: 13, is_ut: false,
  },
  {
    id: 'WB', name: 'West Bengal', capital: 'Kolkata',
    capital_lat: 22.5726, capital_lng: 88.3639,
    geojson_id: 'West Bengal',
    chief_minister: 'Mamata Banerjee', cm_party: 'All India Trinamool Congress', cm_party_color: '#267EC2',
    landmark: 'Howrah Bridge', landmark_emoji: '🌉',
    landmark_desc: 'Iconic cantilever bridge over Hooghly river — one of the busiest bridges in the world',
    ruling_party: 'TMC', formed_year: 1947, districts_count: 23, is_ut: false,
  },
  // Union Territories
  {
    id: 'DL', name: 'Delhi', capital: 'New Delhi',
    capital_lat: 28.6139, capital_lng: 77.2090,
    geojson_id: 'NCT of Delhi',
    chief_minister: 'Rekha Gupta', cm_party: 'Bharatiya Janata Party', cm_party_color: '#FF6B00',
    landmark: 'India Gate', landmark_emoji: '🏛️',
    landmark_desc: 'War memorial dedicated to 82,000 soldiers of the Indian Army — heart of New Delhi',
    ruling_party: 'BJP', formed_year: 1956, districts_count: 11, is_ut: true,
  },
  {
    id: 'JK', name: 'Jammu & Kashmir', capital: 'Srinagar',
    capital_lat: 34.0837, capital_lng: 74.7973,
    geojson_id: 'Jammu and Kashmir',
    chief_minister: 'Omar Abdullah', cm_party: 'Jammu & Kashmir National Conference', cm_party_color: '#22c55e',
    landmark: 'Dal Lake', landmark_emoji: '🏞️',
    landmark_desc: 'Jewel in the crown of Kashmir — famous for its houseboats and shikaras',
    ruling_party: 'NC', formed_year: 2019, districts_count: 20, is_ut: true,
  },
  {
    id: 'LA', name: 'Ladakh', capital: 'Leh',
    capital_lat: 34.1526, capital_lng: 77.5771,
    geojson_id: 'Ladakh',
    chief_minister: 'Lt. Governor (UT)', cm_party: 'Central Government', cm_party_color: '#FF6B00',
    landmark: 'Pangong Lake', landmark_emoji: '🏞️',
    landmark_desc: 'Stunning high-altitude lake at 4,350m — spans India-China border',
    ruling_party: 'BJP', formed_year: 2019, districts_count: 2, is_ut: true,
  },
  {
    id: 'PY', name: 'Puducherry', capital: 'Puducherry',
    capital_lat: 11.9416, capital_lng: 79.8083,
    geojson_id: 'Puducherry',
    chief_minister: 'N. Rangasamy', cm_party: 'AINRC', cm_party_color: '#6366f1',
    landmark: 'Auroville', landmark_emoji: '🌐',
    landmark_desc: 'Experimental universal township founded in 1968 — residents from 50+ countries',
    ruling_party: 'AINRC', formed_year: 1954, districts_count: 4, is_ut: true,
  },
  {
    id: 'AN', name: 'Andaman & Nicobar', capital: 'Port Blair',
    capital_lat: 11.6234, capital_lng: 92.7265,
    geojson_id: 'Andaman and Nicobar',
    chief_minister: 'Lt. Governor (UT)', cm_party: 'Central Government', cm_party_color: '#FF6B00',
    landmark: 'Cellular Jail', landmark_emoji: '🏛️',
    landmark_desc: 'Historic prison used by British to exile political prisoners — National Memorial',
    ruling_party: 'Central', formed_year: 1956, districts_count: 3, is_ut: true,
  },
  {
    id: 'CH', name: 'Chandigarh', capital: 'Chandigarh',
    capital_lat: 30.7333, capital_lng: 76.7794,
    geojson_id: 'Chandigarh',
    chief_minister: 'Lt. Governor (UT)', cm_party: 'Central Government', cm_party_color: '#FF6B00',
    landmark: 'Rock Garden', landmark_emoji: '🏛️',
    landmark_desc: 'Nek Chand\'s surreal sculpture garden made from industrial and urban waste',
    ruling_party: 'Central', formed_year: 1966, districts_count: 1, is_ut: true,
  },
  {
    id: 'DN', name: 'Dadra & Nagar Haveli', capital: 'Silvassa',
    capital_lat: 20.2766, capital_lng: 73.0092,
    geojson_id: 'Dadra and Nagar Haveli',
    chief_minister: 'Lt. Governor (UT)', cm_party: 'Central Government', cm_party_color: '#FF6B00',
    landmark: 'Vanganga Lake Garden', landmark_emoji: '🌿',
    landmark_desc: 'Scenic lake garden and tribal cultural museum in Silvassa',
    ruling_party: 'Central', formed_year: 1961, districts_count: 1, is_ut: true,
  },
  {
    id: 'DD', name: 'Daman & Diu', capital: 'Daman',
    capital_lat: 20.4283, capital_lng: 72.8397,
    geojson_id: 'Daman and Diu',
    chief_minister: 'Lt. Governor (UT)', cm_party: 'Central Government', cm_party_color: '#FF6B00',
    landmark: 'Diu Fort', landmark_emoji: '🏯',
    landmark_desc: 'Portuguese fortress protecting the island — symbol of the colonial era',
    ruling_party: 'Central', formed_year: 1961, districts_count: 2, is_ut: true,
  },
  {
    id: 'LD', name: 'Lakshadweep', capital: 'Kavaratti',
    capital_lat: 10.5626, capital_lng: 72.6369,
    geojson_id: 'Lakshadweep',
    chief_minister: 'Lt. Governor (UT)', cm_party: 'Central Government', cm_party_color: '#FF6B00',
    landmark: 'Agatti Island', landmark_emoji: '🏝️',
    landmark_desc: 'Pristine coral island with India\'s cleanest lagoon — gateway to the archipelago',
    ruling_party: 'Central', formed_year: 1956, districts_count: 1, is_ut: true,
  },
];

export function getStateById(id: string): StateInfo | undefined {
  return INDIA_STATES.find(s => s.id === id);
}

export function getStateByGeoName(name: string): StateInfo | undefined {
  return INDIA_STATES.find(s => s.geojson_id === name || s.name === name);
}

export const MOCK_REPRESENTATIVES = [
  {
    id: '1',
    name: 'Narendra Modi',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Official_portrait_of_Narendra_Modi.jpg/440px-Official_portrait_of_Narendra_Modi.jpg',
    party: 'Bharatiya Janata Party', party_short: 'BJP', party_color: '#FF6B00',
    constituency_id: 'varanasi', constituency_name: 'Varanasi',
    constituency_type: 'parliament' as const,
    state_id: 'UP', state_name: 'Uttar Pradesh',
    tenure_start: '2014-05-26', is_active: true,
    ministry: [{ id: 'm1', representative_id: '1', portfolio: 'Prime Minister of India', level: 'cabinet' as const, from_date: '2014-05-26', is_current: true }],
    education: 'MA Political Science, Gujarat University', age: 74, gender: 'Male',
    attendance_percentage: 0, questions_asked: 0, debates_participated: 0, bills_introduced: 0,
    bio: 'Narendra Damodardas Modi has served as the 14th Prime Minister of India since May 2014.',
  },
];
