import { State } from '@/types';

export const INDIA_STATES: State[] = [
  { id: 'AP', name: 'Andhra Pradesh', capital: 'Amaravati', capital_lat: 16.5193, capital_lng: 80.5161, geojson_id: 'Andhra Pradesh' },
  { id: 'AR', name: 'Arunachal Pradesh', capital: 'Itanagar', capital_lat: 27.0844, capital_lng: 93.6053, geojson_id: 'Arunachal Pradesh' },
  { id: 'AS', name: 'Assam', capital: 'Dispur', capital_lat: 26.1445, capital_lng: 91.7362, geojson_id: 'Assam' },
  { id: 'BR', name: 'Bihar', capital: 'Patna', capital_lat: 25.5941, capital_lng: 85.1376, geojson_id: 'Bihar' },
  { id: 'CG', name: 'Chhattisgarh', capital: 'Raipur', capital_lat: 21.2514, capital_lng: 81.6296, geojson_id: 'Chhattisgarh' },
  { id: 'GA', name: 'Goa', capital: 'Panaji', capital_lat: 15.4909, capital_lng: 73.8278, geojson_id: 'Goa' },
  { id: 'GJ', name: 'Gujarat', capital: 'Gandhinagar', capital_lat: 23.2156, capital_lng: 72.6369, geojson_id: 'Gujarat' },
  { id: 'HR', name: 'Haryana', capital: 'Chandigarh', capital_lat: 30.7333, capital_lng: 76.7794, geojson_id: 'Haryana' },
  { id: 'HP', name: 'Himachal Pradesh', capital: 'Shimla', capital_lat: 31.1048, capital_lng: 77.1734, geojson_id: 'Himachal Pradesh' },
  { id: 'JH', name: 'Jharkhand', capital: 'Ranchi', capital_lat: 23.3441, capital_lng: 85.3096, geojson_id: 'Jharkhand' },
  { id: 'KA', name: 'Karnataka', capital: 'Bengaluru', capital_lat: 12.9716, capital_lng: 77.5946, geojson_id: 'Karnataka' },
  { id: 'KL', name: 'Kerala', capital: 'Thiruvananthapuram', capital_lat: 8.5241, capital_lng: 76.9366, geojson_id: 'Kerala' },
  { id: 'MP', name: 'Madhya Pradesh', capital: 'Bhopal', capital_lat: 23.2599, capital_lng: 77.4126, geojson_id: 'Madhya Pradesh' },
  { id: 'MH', name: 'Maharashtra', capital: 'Mumbai', capital_lat: 19.0760, capital_lng: 72.8777, geojson_id: 'Maharashtra' },
  { id: 'MN', name: 'Manipur', capital: 'Imphal', capital_lat: 24.8170, capital_lng: 93.9368, geojson_id: 'Manipur' },
  { id: 'ML', name: 'Meghalaya', capital: 'Shillong', capital_lat: 25.5788, capital_lng: 91.8933, geojson_id: 'Meghalaya' },
  { id: 'MZ', name: 'Mizoram', capital: 'Aizawl', capital_lat: 23.7271, capital_lng: 92.7176, geojson_id: 'Mizoram' },
  { id: 'NL', name: 'Nagaland', capital: 'Kohima', capital_lat: 25.6747, capital_lng: 94.1086, geojson_id: 'Nagaland' },
  { id: 'OD', name: 'Odisha', capital: 'Bhubaneswar', capital_lat: 20.2961, capital_lng: 85.8245, geojson_id: 'Orissa' },
  { id: 'PB', name: 'Punjab', capital: 'Chandigarh', capital_lat: 30.7333, capital_lng: 76.7794, geojson_id: 'Punjab' },
  { id: 'RJ', name: 'Rajasthan', capital: 'Jaipur', capital_lat: 26.9124, capital_lng: 75.7873, geojson_id: 'Rajasthan' },
  { id: 'SK', name: 'Sikkim', capital: 'Gangtok', capital_lat: 27.3314, capital_lng: 88.6138, geojson_id: 'Sikkim' },
  { id: 'TN', name: 'Tamil Nadu', capital: 'Chennai', capital_lat: 13.0827, capital_lng: 80.2707, geojson_id: 'Tamil Nadu' },
  { id: 'TG', name: 'Telangana', capital: 'Hyderabad', capital_lat: 17.3850, capital_lng: 78.4867, geojson_id: 'Telangana' },
  { id: 'TR', name: 'Tripura', capital: 'Agartala', capital_lat: 23.8315, capital_lng: 91.2868, geojson_id: 'Tripura' },
  { id: 'UP', name: 'Uttar Pradesh', capital: 'Lucknow', capital_lat: 26.8467, capital_lng: 80.9462, geojson_id: 'Uttar Pradesh' },
  { id: 'UK', name: 'Uttarakhand', capital: 'Dehradun', capital_lat: 30.3165, capital_lng: 78.0322, geojson_id: 'Uttaranchal' },
  { id: 'WB', name: 'West Bengal', capital: 'Kolkata', capital_lat: 22.5726, capital_lng: 88.3639, geojson_id: 'West Bengal' },
  // UTs
  { id: 'DL', name: 'Delhi', capital: 'New Delhi', capital_lat: 28.6139, capital_lng: 77.2090, geojson_id: 'NCT of Delhi' },
  { id: 'JK', name: 'Jammu & Kashmir', capital: 'Srinagar', capital_lat: 34.0837, capital_lng: 74.7973, geojson_id: 'Jammu and Kashmir' },
  { id: 'LA', name: 'Ladakh', capital: 'Leh', capital_lat: 34.1526, capital_lng: 77.5771, geojson_id: 'Ladakh' },
  { id: 'PY', name: 'Puducherry', capital: 'Puducherry', capital_lat: 11.9416, capital_lng: 79.8083, geojson_id: 'Puducherry' },
  { id: 'AN', name: 'Andaman & Nicobar', capital: 'Port Blair', capital_lat: 11.6234, capital_lng: 92.7265, geojson_id: 'Andaman and Nicobar' },
  { id: 'CH', name: 'Chandigarh', capital: 'Chandigarh', capital_lat: 30.7333, capital_lng: 76.7794, geojson_id: 'Chandigarh' },
  { id: 'DN', name: 'Dadra & Nagar Haveli', capital: 'Silvassa', capital_lat: 20.2766, capital_lng: 73.0092, geojson_id: 'Dadra and Nagar Haveli' },
  { id: 'DD', name: 'Daman & Diu', capital: 'Daman', capital_lat: 20.4283, capital_lng: 72.8397, geojson_id: 'Daman and Diu' },
  { id: 'LD', name: 'Lakshadweep', capital: 'Kavaratti', capital_lat: 10.5626, capital_lng: 72.6369, geojson_id: 'Lakshadweep' },
];

export const MOCK_REPRESENTATIVES = [
  {
    id: '1',
    name: 'Narendra Modi',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Official_portrait_of_Narendra_Modi.jpg/440px-Official_portrait_of_Narendra_Modi.jpg',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    party_color: '#FF6B00',
    constituency_id: 'varanasi',
    constituency_name: 'Varanasi',
    constituency_type: 'parliament' as const,
    state_id: 'UP',
    state_name: 'Uttar Pradesh',
    tenure_start: '2014-05-26',
    is_active: true,
    ministry: [
      { id: 'm1', representative_id: '1', portfolio: 'Prime Minister of India', level: 'cabinet' as const, from_date: '2014-05-26', is_current: true },
    ],
    education: 'MA in Political Science, Gujarat University',
    age: 74,
    gender: 'Male',
    attendance_percentage: 0,
    questions_asked: 0,
    debates_participated: 0,
    bills_introduced: 0,
    bio: 'Narendra Damodardas Modi is an Indian politician who has served as the 14th and current Prime Minister of India since May 2014. He is a member of the BJP and of the RSS.',
  },
  {
    id: '2',
    name: 'Rahul Gandhi',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Rahul_Gandhi.jpg/440px-Rahul_Gandhi.jpg',
    party: 'Indian National Congress',
    party_short: 'INC',
    party_color: '#19AAED',
    constituency_id: 'wayanad',
    constituency_name: 'Wayanad',
    constituency_type: 'parliament' as const,
    state_id: 'KL',
    state_name: 'Kerala',
    tenure_start: '2019-05-23',
    is_active: true,
    ministry: [],
    education: 'BA, Trinity College, Cambridge; MPhil, Cambridge',
    age: 54,
    gender: 'Male',
    attendance_percentage: 72,
    questions_asked: 45,
    debates_participated: 38,
    bills_introduced: 2,
    bio: 'Rahul Gandhi is an Indian politician and the leader of the Indian National Congress party. He previously served as president of the INC from 2017 to 2019.',
  },
];
