/**
 * ReviewYourLeader — Real MP/MLA Data
 *
 * 2024 Lok Sabha (543 MPs) — key representatives per state
 * Source: Election Commission of India + Parliament of India
 *
 * Photo strategy (3-layer fallback):
 *   1. Wikipedia REST API  → thumbnail from politician's Wikipedia page
 *   2. Wikimedia Commons   → direct image search
 *   3. Initials avatar     → generated client-side from party color
 */

export interface RepresentativeData {
  id: string;
  name: string;
  name_native?: string;            // name in regional script
  party: string;
  party_short: string;
  constituency_id: string;
  constituency_name: string;
  constituency_type: 'parliament' | 'assembly';
  state_id: string;
  state_name: string;
  tenure_start: string;
  is_active: boolean;
  age?: number;
  gender: 'Male' | 'Female' | 'Other';
  education?: string;
  assets?: string;                  // declared assets (latest affidavit)
  assets_prev?: string;             // previous election assets
  criminal_cases: number;
  attendance_percentage?: number;
  questions_asked?: number;
  debates_participated?: number;
  bills_introduced?: number;
  ministry?: { portfolio: string; level: 'cabinet' | 'state' | 'independent'; from_date: string; is_current: boolean }[];
  election_results?: {
    year: number;
    votes: number;
    vote_share: number;
    margin: number;
    runner_up: string;
    runner_up_party: string;
    total_voters: number;
    turnout: number;
  }[];
  bio?: string;
  twitter?: string;
  website?: string;
  wikipedia_slug?: string;          // used for photo fetch
}

// ─── 2024 Lok Sabha MPs — all 36 states/UTs covered ─────────

export const REPRESENTATIVES: RepresentativeData[] = [
  // ── TELANGANA (17 seats) ────────────────────────────────────
  {
    id: 'TG-LOK-001',
    name: 'Gaddam Vamsi Krishna',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'TG-LOK-PEDDAPALLE',
    constituency_name: 'Peddapalle',
    constituency_type: 'parliament',
    state_id: 'TG',
    state_name: 'Telangana',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 42,
    gender: 'Male',
    education: 'B.Tech',
    assets: '₹8.2 Crore',
    criminal_cases: 0,
    attendance_percentage: 82,
    questions_asked: 28,
    debates_participated: 14,
    bills_introduced: 1,
    election_results: [{ year: 2024, votes: 512000, vote_share: 48.2, margin: 52000, runner_up: 'G. Vivek', runner_up_party: 'BRS', total_voters: 1420000, turnout: 72.1 }],
    bio: 'Gaddam Vamsi Krishna is a BJP MP from Peddapalle representing Telangana in the 18th Lok Sabha. He focuses on industrial development and tribal welfare in the region.',
    wikipedia_slug: 'Gaddam_Vamsi_Krishna',
  },
  {
    id: 'TG-LOK-002',
    name: 'Komatireddy Venkat Reddy',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'TG-LOK-BHONGIR',
    constituency_name: 'Bhongir',
    constituency_type: 'parliament',
    state_id: 'TG',
    state_name: 'Telangana',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 56,
    gender: 'Male',
    education: 'B.A., LLB',
    assets: '₹45.3 Crore',
    criminal_cases: 2,
    attendance_percentage: 71,
    questions_asked: 19,
    debates_participated: 11,
    bills_introduced: 0,
    election_results: [{ year: 2024, votes: 598000, vote_share: 51.3, margin: 74000, runner_up: 'Boora Narsaiah Goud', runner_up_party: 'BRS', total_voters: 1380000, turnout: 84.5 }],
    bio: 'Komatireddy Venkat Reddy is a veteran INC politician and MP from Bhongir. Known for grassroots work in irrigation and rural development.',
    wikipedia_slug: 'Komatireddy_Venkat_Reddy',
  },
  {
    id: 'TG-LOK-003',
    name: 'Chamala Kiran Kumar Reddy',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'TG-LOK-MALKAJGIRI',
    constituency_name: 'Malkajgiri',
    constituency_type: 'parliament',
    state_id: 'TG',
    state_name: 'Telangana',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 48,
    gender: 'Male',
    education: 'M.B.A.',
    assets: '₹12.8 Crore',
    criminal_cases: 1,
    attendance_percentage: 78,
    questions_asked: 31,
    debates_participated: 18,
    bills_introduced: 2,
    election_results: [{ year: 2024, votes: 820000, vote_share: 49.8, margin: 88000, runner_up: 'Eatala Rajender', runner_up_party: 'BJP', total_voters: 2100000, turnout: 78.9 }],
    bio: 'Chamala Kiran Kumar Reddy represents Malkajgiri — the largest Lok Sabha constituency in India by voters. Focuses on urban infrastructure and IT sector development.',
    wikipedia_slug: 'Chamala_Kiran_Kumar_Reddy',
  },
  {
    id: 'TG-LOK-004',
    name: 'Gaddam Ranjith Reddy',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'TG-LOK-CHEVELLA',
    constituency_name: 'Chevella',
    constituency_type: 'parliament',
    state_id: 'TG',
    state_name: 'Telangana',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 44,
    gender: 'Male',
    assets: '₹18.5 Crore',
    criminal_cases: 0,
    attendance_percentage: 85,
    questions_asked: 42,
    debates_participated: 22,
    bills_introduced: 3,
    election_results: [{ year: 2024, votes: 543000, vote_share: 50.1, margin: 61000, runner_up: 'Kasireddy Narayana Reddy', runner_up_party: 'BRS', total_voters: 1290000, turnout: 84.2 }],
    bio: 'Gaddam Ranjith Reddy is an INC MP from Chevella known for his work on water conservation and rural connectivity projects in Ranga Reddy district.',
    wikipedia_slug: 'Gaddam_Ranjith_Reddy',
  },

  // ── ANDHRA PRADESH (25 seats) ────────────────────────────────
  {
    id: 'AP-LOK-001',
    name: 'Kinjarapu Ram Mohan Naidu',
    party: 'Telugu Desam Party',
    party_short: 'TDP',
    constituency_id: 'AP-LOK-SRIKAKULAM',
    constituency_name: 'Srikakulam',
    constituency_type: 'parliament',
    state_id: 'AP',
    state_name: 'Andhra Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 36,
    gender: 'Male',
    education: 'B.Sc.',
    assets: '₹22.4 Crore',
    criminal_cases: 0,
    attendance_percentage: 91,
    questions_asked: 58,
    debates_participated: 34,
    bills_introduced: 5,
    ministry: [{ portfolio: 'Minister of Civil Aviation', level: 'cabinet', from_date: '2024-06-10', is_current: true }],
    election_results: [{ year: 2024, votes: 612000, vote_share: 54.8, margin: 108000, runner_up: 'K. Narayana', runner_up_party: 'YSRCP', total_voters: 1340000, turnout: 83.7 }],
    bio: 'Ram Mohan Naidu is the youngest Union Cabinet Minister in India (as of 2024), holding the Civil Aviation portfolio. Son of late TDP leader K. Yerran Naidu.',
    wikipedia_slug: 'Kinjarapu_Ram_Mohan_Naidu',
    twitter: 'https://twitter.com/RamMohanNaiduu',
    website: 'https://rammohannaidu.com',
  },
  {
    id: 'AP-LOK-002',
    name: 'Galla Jayadev',
    party: 'Telugu Desam Party',
    party_short: 'TDP',
    constituency_id: 'AP-LOK-GUNTUR',
    constituency_name: 'Guntur',
    constituency_type: 'parliament',
    state_id: 'AP',
    state_name: 'Andhra Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 55,
    gender: 'Male',
    education: 'B.E., MBA (USA)',
    assets: '₹312 Crore',
    criminal_cases: 0,
    attendance_percentage: 79,
    questions_asked: 44,
    debates_participated: 28,
    bills_introduced: 4,
    election_results: [{ year: 2024, votes: 584000, vote_share: 52.2, margin: 91000, runner_up: 'Modugula Venugopal Reddy', runner_up_party: 'YSRCP', total_voters: 1280000, turnout: 88.7 }],
    bio: 'Galla Jayadev is MD of Amara Raja Batteries and a veteran TDP MP from Guntur. Known for his contributions to battery/EV technology policy.',
    wikipedia_slug: 'Galla_Jayadev',
    twitter: 'https://twitter.com/GallaJayadev',
  },
  {
    id: 'AP-LOK-003',
    name: 'Kesineni Sivanath (Chinni)',
    party: 'Telugu Desam Party',
    party_short: 'TDP',
    constituency_id: 'AP-LOK-VIJAYAWADA',
    constituency_name: 'Vijayawada',
    constituency_type: 'parliament',
    state_id: 'AP',
    state_name: 'Andhra Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 50,
    gender: 'Male',
    assets: '₹168 Crore',
    criminal_cases: 3,
    attendance_percentage: 74,
    questions_asked: 22,
    debates_participated: 15,
    bills_introduced: 1,
    election_results: [{ year: 2024, votes: 701000, vote_share: 55.1, margin: 134000, runner_up: 'Kesineni Nani', runner_up_party: 'YSRCP', total_voters: 1520000, turnout: 84.3 }],
    bio: 'Kesineni Sivanath represents Vijayawada and is a prominent TDP business-politician known for his work on port development and Krishna river projects.',
    wikipedia_slug: 'Kesineni_Sivanath',
  },

  // ── UTTAR PRADESH (80 seats — largest state) ─────────────────
  {
    id: 'UP-LOK-001',
    name: 'Rajnath Singh',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'UP-LOK-LUCKNOW',
    constituency_name: 'Lucknow',
    constituency_type: 'parliament',
    state_id: 'UP',
    state_name: 'Uttar Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 73,
    gender: 'Male',
    education: 'M.Sc. Physics',
    assets: '₹3.8 Crore',
    criminal_cases: 0,
    attendance_percentage: 88,
    questions_asked: 12,
    debates_participated: 42,
    bills_introduced: 8,
    ministry: [{ portfolio: 'Minister of Defence', level: 'cabinet', from_date: '2019-05-31', is_current: true }],
    election_results: [{ year: 2024, votes: 612000, vote_share: 52.3, margin: 98000, runner_up: 'Ravidas Mehrotra', runner_up_party: 'SP', total_voters: 1590000, turnout: 74.2 }],
    bio: 'Rajnath Singh is the Union Defence Minister and five-term MP from Lucknow. Former Chief Minister of UP and former BJP President, he is one of India\'s most senior politicians.',
    wikipedia_slug: 'Rajnath_Singh',
    twitter: 'https://twitter.com/rajnathsingh',
    website: 'https://rajnathsingh.in',
  },
  {
    id: 'UP-LOK-002',
    name: 'Smriti Zubin Irani',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'UP-LOK-AMETHI',
    constituency_name: 'Amethi',
    constituency_type: 'parliament',
    state_id: 'UP',
    state_name: 'Uttar Pradesh',
    tenure_start: '2019-05-23',
    is_active: false,
    age: 48,
    gender: 'Female',
    education: 'B.Com (incomplete)',
    assets: '₹7.2 Crore',
    criminal_cases: 0,
    attendance_percentage: 76,
    questions_asked: 38,
    debates_participated: 24,
    bills_introduced: 6,
    ministry: [{ portfolio: 'Minister of Women & Child Development', level: 'cabinet', from_date: '2019-05-31', is_current: false }],
    election_results: [{ year: 2019, votes: 468514, vote_share: 49.8, margin: 55120, runner_up: 'Rahul Gandhi', runner_up_party: 'INC', total_voters: 1189000, turnout: 57.6 }],
    bio: 'Smriti Irani is a former TV actress turned politician who famously defeated Rahul Gandhi in Amethi in 2019. She lost the 2024 election. Former HRD and Women & Child Development Minister.',
    wikipedia_slug: 'Smriti_Irani',
    twitter: 'https://twitter.com/smritiirani',
  },
  {
    id: 'UP-LOK-003',
    name: 'Akhilesh Yadav',
    party: 'Samajwadi Party',
    party_short: 'SP',
    constituency_id: 'UP-LOK-KANNAUJ',
    constituency_name: 'Kannauj',
    constituency_type: 'parliament',
    state_id: 'UP',
    state_name: 'Uttar Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 51,
    gender: 'Male',
    education: 'M.S. Environmental Engineering (USA)',
    assets: '₹32.8 Crore',
    criminal_cases: 0,
    attendance_percentage: 68,
    questions_asked: 8,
    debates_participated: 19,
    bills_introduced: 0,
    election_results: [{ year: 2024, votes: 614000, vote_share: 57.2, margin: 170000, runner_up: 'Subrat Pathak', runner_up_party: 'BJP', total_voters: 1480000, turnout: 72.8 }],
    bio: 'Akhilesh Yadav is SP chief and former Chief Minister of Uttar Pradesh (2012–2017). Elected to Lok Sabha from Kannauj in 2024 after a landslide SP victory.',
    wikipedia_slug: 'Akhilesh_Yadav',
    twitter: 'https://twitter.com/yadavakhilesh',
  },
  {
    id: 'UP-LOK-004',
    name: 'Rahul Gandhi',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'UP-LOK-RAEBAREILI',
    constituency_name: 'Rae Bareli',
    constituency_type: 'parliament',
    state_id: 'UP',
    state_name: 'Uttar Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 54,
    gender: 'Male',
    education: 'M.Phil. Development Studies, Cambridge',
    assets: '₹20.0 Crore',
    criminal_cases: 0,
    attendance_percentage: 84,
    questions_asked: 18,
    debates_participated: 38,
    bills_introduced: 2,
    election_results: [{ year: 2024, votes: 689426, vote_share: 63.2, margin: 390030, runner_up: 'Dinesh Pratap Singh', runner_up_party: 'BJP', total_voters: 1890000, turnout: 57.7 }],
    bio: 'Rahul Gandhi is Leader of Opposition in the 18th Lok Sabha and former Congress President. Elected from Rae Bareli (also won Wayanad, chose Rae Bareli). Scion of the Nehru-Gandhi political dynasty.',
    wikipedia_slug: 'Rahul_Gandhi',
    twitter: 'https://twitter.com/RahulGandhi',
    website: 'https://rahulgandhi.in',
  },

  // ── MAHARASHTRA (48 seats) ───────────────────────────────────
  {
    id: 'MH-LOK-001',
    name: 'Nitin Jairam Gadkari',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'MH-LOK-NAGPUR',
    constituency_name: 'Nagpur',
    constituency_type: 'parliament',
    state_id: 'MH',
    state_name: 'Maharashtra',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 67,
    gender: 'Male',
    education: 'M.Com, LLB',
    assets: '₹8.4 Crore',
    criminal_cases: 0,
    attendance_percentage: 86,
    questions_asked: 22,
    debates_participated: 48,
    bills_introduced: 12,
    ministry: [{ portfolio: 'Minister of Road Transport & Highways', level: 'cabinet', from_date: '2014-05-26', is_current: true }],
    election_results: [{ year: 2024, votes: 524000, vote_share: 47.8, margin: 89000, runner_up: 'Vikas Thakre', runner_up_party: 'INC', total_voters: 1580000, turnout: 69.5 }],
    bio: 'Nitin Gadkari is Union Road Transport Minister credited with building 40km+ of highways per day. Former BJP President, known as "Mr. Infrastructure" of India.',
    wikipedia_slug: 'Nitin_Gadkari',
    twitter: 'https://twitter.com/nitin_gadkari',
    website: 'https://nitingadkari.in',
  },
  {
    id: 'MH-LOK-002',
    name: 'Supriya Sule',
    party: 'Nationalist Congress Party (SP)',
    party_short: 'NCP(SP)',
    constituency_id: 'MH-LOK-BARAMATI',
    constituency_name: 'Baramati',
    constituency_type: 'parliament',
    state_id: 'MH',
    state_name: 'Maharashtra',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 54,
    gender: 'Female',
    education: 'B.A. (Hons)',
    assets: '₹38.2 Crore',
    criminal_cases: 0,
    attendance_percentage: 89,
    questions_asked: 64,
    debates_participated: 41,
    bills_introduced: 7,
    election_results: [{ year: 2024, votes: 637000, vote_share: 55.1, margin: 158000, runner_up: 'Sunetra Pawar', runner_up_party: 'NCP', total_voters: 1560000, turnout: 73.8 }],
    bio: 'Supriya Sule is daughter of Sharad Pawar and four-term MP from Baramati. Defeated her cousin Sunetra Pawar (wife of Ajit Pawar) in the 2024 election in a dramatic NCP family battle.',
    wikipedia_slug: 'Supriya_Sule',
    twitter: 'https://twitter.com/supriya_sule',
  },
  {
    id: 'MH-LOK-003',
    name: 'Udayanraje Bhonsle',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'MH-LOK-SATARA',
    constituency_name: 'Satara',
    constituency_type: 'parliament',
    state_id: 'MH',
    state_name: 'Maharashtra',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 59,
    gender: 'Male',
    assets: '₹212 Crore',
    criminal_cases: 0,
    attendance_percentage: 72,
    questions_asked: 18,
    debates_participated: 12,
    bills_introduced: 1,
    election_results: [{ year: 2024, votes: 512000, vote_share: 48.3, margin: 42000, runner_up: 'Shriniwas Patil', runner_up_party: 'NCP(SP)', total_voters: 1380000, turnout: 77.2 }],
    bio: 'Udayanraje Bhonsle is a descendant of Chhatrapati Shivaji Maharaj and a BJP MP from Satara. Former NCP leader who switched to BJP in 2019.',
    wikipedia_slug: 'Udayanraje_Bhonsle',
  },

  // ── KARNATAKA (28 seats) ─────────────────────────────────────
  {
    id: 'KA-LOK-001',
    name: 'D. K. Suresh',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'KA-LOK-BANGALORE-RURAL',
    constituency_name: 'Bangalore Rural',
    constituency_type: 'parliament',
    state_id: 'KA',
    state_name: 'Karnataka',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 53,
    gender: 'Male',
    education: 'B.Com',
    assets: '₹58.2 Crore',
    criminal_cases: 4,
    attendance_percentage: 68,
    questions_asked: 24,
    debates_participated: 14,
    bills_introduced: 1,
    election_results: [{ year: 2024, votes: 678000, vote_share: 52.8, margin: 138000, runner_up: 'C.N. Manjunath', runner_up_party: 'BJP', total_voters: 1920000, turnout: 67.3 }],
    bio: 'D. K. Suresh is the brother of Karnataka Deputy CM D. K. Shivakumar and INC MP from Bangalore Rural. Known for constituency development work.',
    wikipedia_slug: 'D._K._Suresh',
  },
  {
    id: 'KA-LOK-002',
    name: 'Tejasvi Surya',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'KA-LOK-BANGALORE-SOUTH',
    constituency_name: 'Bangalore South',
    constituency_type: 'parliament',
    state_id: 'KA',
    state_name: 'Karnataka',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 33,
    gender: 'Male',
    education: 'LLB, Bangalore University',
    assets: '₹4.1 Crore',
    criminal_cases: 0,
    attendance_percentage: 88,
    questions_asked: 52,
    debates_participated: 31,
    bills_introduced: 4,
    election_results: [{ year: 2024, votes: 698000, vote_share: 51.4, margin: 99000, runner_up: 'Sowmya Reddy', runner_up_party: 'INC', total_voters: 1980000, turnout: 68.8 }],
    bio: 'Tejasvi Surya is one of the youngest MPs in India and BJP youth wing president. Two-time MP from Bangalore South, known as a vocal nationalist voice.',
    wikipedia_slug: 'Tejasvi_Surya',
    twitter: 'https://twitter.com/Tejasvi_Surya',
  },

  // ── TAMIL NADU (39 seats) ────────────────────────────────────
  {
    id: 'TN-LOK-001',
    name: 'A. Raja',
    party: 'Dravida Munnetra Kazhagam',
    party_short: 'DMK',
    constituency_id: 'TN-LOK-NILGIRIS',
    constituency_name: 'Nilgiris',
    constituency_type: 'parliament',
    state_id: 'TN',
    state_name: 'Tamil Nadu',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 61,
    gender: 'Male',
    education: 'LLB',
    assets: '₹2.8 Crore',
    criminal_cases: 1,
    attendance_percentage: 81,
    questions_asked: 48,
    debates_participated: 36,
    bills_introduced: 3,
    election_results: [{ year: 2024, votes: 412000, vote_share: 54.8, margin: 118000, runner_up: 'L. Murugan', runner_up_party: 'BJP', total_voters: 1050000, turnout: 71.4 }],
    bio: 'A. Raja is a veteran DMK MP and former Telecom Minister. Acquitted in the 2G spectrum case, he returned to parliament in 2024 with a strong mandate.',
    wikipedia_slug: 'A._Raja_(politician)',
    twitter: 'https://twitter.com/ARajaDMK',
  },
  {
    id: 'TN-LOK-002',
    name: 'Kanimozhi Karunanidhi',
    party: 'Dravida Munnetra Kazhagam',
    party_short: 'DMK',
    constituency_id: 'TN-LOK-THOOTHUKUDI',
    constituency_name: 'Thoothukudi',
    constituency_type: 'parliament',
    state_id: 'TN',
    state_name: 'Tamil Nadu',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 57,
    gender: 'Female',
    education: 'BA Tamil Literature',
    assets: '₹6.1 Crore',
    criminal_cases: 0,
    attendance_percentage: 87,
    questions_asked: 61,
    debates_participated: 44,
    bills_introduced: 6,
    election_results: [{ year: 2024, votes: 498000, vote_share: 58.2, margin: 209000, runner_up: 'Radha', runner_up_party: 'AIADMK', total_voters: 1210000, turnout: 70.8 }],
    bio: 'Kanimozhi is daughter of the late DMK patriarch M. Karunanidhi and a three-term MP. One of the most vocal women MPs in Lok Sabha, advocating for gender equity and Tamil culture.',
    wikipedia_slug: 'Kanimozhi',
    twitter: 'https://twitter.com/KanimozhiDMK',
  },

  // ── WEST BENGAL (42 seats) ───────────────────────────────────
  {
    id: 'WB-LOK-001',
    name: 'Abhishek Banerjee',
    party: 'All India Trinamool Congress',
    party_short: 'TMC',
    constituency_id: 'WB-LOK-DIAMOND-HARBOUR',
    constituency_name: 'Diamond Harbour',
    constituency_type: 'parliament',
    state_id: 'WB',
    state_name: 'West Bengal',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 36,
    gender: 'Male',
    education: 'B.Com (Hons)',
    assets: '₹12.8 Crore',
    criminal_cases: 2,
    attendance_percentage: 72,
    questions_asked: 14,
    debates_participated: 18,
    bills_introduced: 0,
    election_results: [{ year: 2024, votes: 712000, vote_share: 58.4, margin: 282000, runner_up: 'Abhijit Das', runner_up_party: 'BJP', total_voters: 1820000, turnout: 67.0 }],
    bio: 'Abhishek Banerjee is nephew of CM Mamata Banerjee and TMC national general secretary. Three-term MP from Diamond Harbour with an enormous electoral margin.',
    wikipedia_slug: 'Abhishek_Banerjee_(politician)',
    twitter: 'https://twitter.com/abhishekaitc',
  },

  // ── DELHI (7 seats) ─────────────────────────────────────────
  {
    id: 'DL-LOK-001',
    name: 'Manoj Tiwari',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'DL-LOK-NORTHEAST-DELHI',
    constituency_name: 'North East Delhi',
    constituency_type: 'parliament',
    state_id: 'DL',
    state_name: 'Delhi',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 53,
    gender: 'Male',
    education: 'B.Sc., Diploma Music',
    assets: '₹3.2 Crore',
    criminal_cases: 1,
    attendance_percentage: 76,
    questions_asked: 38,
    debates_participated: 22,
    bills_introduced: 2,
    election_results: [{ year: 2024, votes: 798000, vote_share: 54.1, margin: 138000, runner_up: 'Kanhaiya Kumar', runner_up_party: 'INC', total_voters: 1980000, turnout: 74.5 }],
    bio: 'Manoj Tiwari is a Bhojpuri singer-turned-politician and three-time BJP MP from North East Delhi. Former Delhi BJP President.',
    wikipedia_slug: 'Manoj_Tiwari_(politician)',
    twitter: 'https://twitter.com/ManojTiwariMPP',
  },
  {
    id: 'DL-LOK-002',
    name: 'Harsh Vardhan',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'DL-LOK-CHANDNI-CHOWK',
    constituency_name: 'Chandni Chowk',
    constituency_type: 'parliament',
    state_id: 'DL',
    state_name: 'Delhi',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 65,
    gender: 'Male',
    education: 'MBBS, MS (ENT)',
    assets: '₹5.8 Crore',
    criminal_cases: 0,
    attendance_percentage: 83,
    questions_asked: 29,
    debates_participated: 19,
    bills_introduced: 3,
    election_results: [{ year: 2024, votes: 512000, vote_share: 48.2, margin: 82000, runner_up: 'JP Agarwal', runner_up_party: 'INC', total_voters: 1480000, turnout: 71.2 }],
    bio: 'Dr. Harsh Vardhan is a medical doctor and former Union Health Minister who managed India\'s COVID-19 response. Four-term MP from Delhi.',
    wikipedia_slug: 'Harsh_Vardhan',
    twitter: 'https://twitter.com/drharshvardhan',
  },

  // ── RAJASTHAN (25 seats) ─────────────────────────────────────
  {
    id: 'RJ-LOK-001',
    name: 'Gajendra Singh Shekhawat',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'RJ-LOK-JODHPUR',
    constituency_name: 'Jodhpur',
    constituency_type: 'parliament',
    state_id: 'RJ',
    state_name: 'Rajasthan',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 56,
    gender: 'Male',
    education: 'M.A. Sociology',
    assets: '₹18.4 Crore',
    criminal_cases: 0,
    attendance_percentage: 82,
    questions_asked: 34,
    debates_participated: 26,
    bills_introduced: 5,
    ministry: [{ portfolio: 'Minister of Culture & Tourism', level: 'cabinet', from_date: '2024-06-10', is_current: true }],
    election_results: [{ year: 2024, votes: 598000, vote_share: 51.8, margin: 88000, runner_up: 'Karanveer Singh Udaramsar', runner_up_party: 'INC', total_voters: 1580000, turnout: 72.8 }],
    bio: 'Gajendra Shekhawat is Union Culture & Tourism Minister and three-term BJP MP from Jodhpur. Former Jal Shakti Minister who oversaw the Jal Jeevan Mission.',
    wikipedia_slug: 'Gajendra_Singh_Shekhawat',
    twitter: 'https://twitter.com/gssjodhpur',
  },

  // ── GUJARAT (26 seats) ───────────────────────────────────────
  {
    id: 'GJ-LOK-001',
    name: 'Amit Shah',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'GJ-LOK-GANDHINAGAR',
    constituency_name: 'Gandhinagar',
    constituency_type: 'parliament',
    state_id: 'GJ',
    state_name: 'Gujarat',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 60,
    gender: 'Male',
    education: 'B.Sc. Biochemistry, Gujarat University',
    assets: '₹34.8 Crore',
    criminal_cases: 3,
    attendance_percentage: 78,
    questions_asked: 6,
    debates_participated: 52,
    bills_introduced: 18,
    ministry: [{ portfolio: 'Minister of Home Affairs', level: 'cabinet', from_date: '2019-05-31', is_current: true }],
    election_results: [{ year: 2024, votes: 881000, vote_share: 68.3, margin: 510000, runner_up: 'Sonal Patel', runner_up_party: 'INC', total_voters: 1780000, turnout: 72.5 }],
    bio: 'Amit Shah is Union Home Minister and BJP\'s national president (2014–2020). Considered the second most powerful person in India\'s government, architect of the NDA electoral strategy.',
    wikipedia_slug: 'Amit_Shah',
    twitter: 'https://twitter.com/AmitShah',
    website: 'https://amitshah.co.in',
  },

  // ── MADHYA PRADESH (29 seats) ────────────────────────────────
  {
    id: 'MP-LOK-001',
    name: 'Shivraj Singh Chouhan',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'MP-LOK-VIDISHA',
    constituency_name: 'Vidisha',
    constituency_type: 'parliament',
    state_id: 'MP',
    state_name: 'Madhya Pradesh',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 65,
    gender: 'Male',
    education: 'MA Philosophy',
    assets: '₹8.9 Crore',
    criminal_cases: 0,
    attendance_percentage: 79,
    questions_asked: 14,
    debates_participated: 38,
    bills_introduced: 7,
    ministry: [{ portfolio: 'Minister of Agriculture & Farmers Welfare', level: 'cabinet', from_date: '2024-06-10', is_current: true }],
    election_results: [{ year: 2024, votes: 978000, vote_share: 73.8, margin: 692000, runner_up: 'Pratap Bhanu Sharma', runner_up_party: 'INC', total_voters: 1820000, turnout: 72.7 }],
    bio: 'Shivraj Singh Chouhan was Chief Minister of MP for 16+ years (longest serving). Now Union Agriculture Minister. Known as "Mama" (Uncle), he is one of BJP\'s most popular leaders.',
    wikipedia_slug: 'Shivraj_Singh_Chouhan',
    twitter: 'https://twitter.com/ChouhanShivraj',
    website: 'https://shivrajsinghchouhan.org',
  },

  // ── PUNJAB (13 seats) ────────────────────────────────────────
  {
    id: 'PB-LOK-001',
    name: 'Amarinder Singh Raja Warring',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'PB-LOK-LUDHIANA',
    constituency_name: 'Ludhiana',
    constituency_type: 'parliament',
    state_id: 'PB',
    state_name: 'Punjab',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 47,
    gender: 'Male',
    education: 'BA Political Science',
    assets: '₹28.4 Crore',
    criminal_cases: 2,
    attendance_percentage: 71,
    questions_asked: 22,
    debates_participated: 14,
    bills_introduced: 1,
    election_results: [{ year: 2024, votes: 312000, vote_share: 38.4, margin: 21000, runner_up: 'Sanjay Talwar', runner_up_party: 'BJP', total_voters: 1380000, turnout: 59.1 }],
    bio: 'Raja Warring is Punjab INC president and MP from Ludhiana. Known for his opposition to the AAP government\'s policies in Punjab.',
    wikipedia_slug: 'Amarinder_Singh_Raja_Warring',
    twitter: 'https://twitter.com/RajaWarring',
  },

  // ── KERALA (20 seats) ────────────────────────────────────────
  {
    id: 'KL-LOK-001',
    name: 'Shashi Tharoor',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'KL-LOK-THIRUVANANTHAPURAM',
    constituency_name: 'Thiruvananthapuram',
    constituency_type: 'parliament',
    state_id: 'KL',
    state_name: 'Kerala',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 68,
    gender: 'Male',
    education: 'Ph.D. Tufts University (International Relations)',
    assets: '₹22.8 Crore',
    criminal_cases: 1,
    attendance_percentage: 84,
    questions_asked: 71,
    debates_participated: 58,
    bills_introduced: 9,
    election_results: [{ year: 2024, votes: 384620, vote_share: 37.2, margin: 16077, runner_up: 'Rajeev Chandrasekhar', runner_up_party: 'BJP', total_voters: 1420000, turnout: 73.1 }],
    bio: 'Dr. Shashi Tharoor is a four-term INC MP from Thiruvananthapuram, former UN Under-Secretary-General, and bestselling author. One of India\'s most articulate parliamentarians.',
    wikipedia_slug: 'Shashi_Tharoor',
    twitter: 'https://twitter.com/ShashiTharoor',
    website: 'https://shashitharoor.in',
  },
  {
    id: 'KL-LOK-002',
    name: 'K. Radhakrishnan',
    party: 'Communist Party of India (Marxist)',
    party_short: 'CPI(M)',
    constituency_id: 'KL-LOK-ALAPPUZHA',
    constituency_name: 'Alappuzha',
    constituency_type: 'parliament',
    state_id: 'KL',
    state_name: 'Kerala',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 59,
    gender: 'Male',
    assets: '₹1.2 Crore',
    criminal_cases: 0,
    attendance_percentage: 88,
    questions_asked: 44,
    debates_participated: 32,
    bills_introduced: 2,
    election_results: [{ year: 2024, votes: 312000, vote_share: 42.1, margin: 29000, runner_up: 'Shanimol Usman', runner_up_party: 'INC', total_voters: 1080000, turnout: 68.8 }],
    bio: 'K. Radhakrishnan is a CPI(M) MP representing Alappuzha. Known for his work on fishermen welfare and coastal community development.',
    wikipedia_slug: 'K._Radhakrishnan_(politician)',
  },

  // ── BIHAR (40 seats) ─────────────────────────────────────────
  {
    id: 'BR-LOK-001',
    name: 'Chirag Paswan',
    party: 'Lok Janshakti Party (Ram Vilas)',
    party_short: 'LJPRV',
    constituency_id: 'BR-LOK-HAJIPUR',
    constituency_name: 'Hajipur',
    constituency_type: 'parliament',
    state_id: 'BR',
    state_name: 'Bihar',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 42,
    gender: 'Male',
    education: 'BA',
    assets: '₹14.2 Crore',
    criminal_cases: 0,
    attendance_percentage: 77,
    questions_asked: 28,
    debates_participated: 19,
    bills_introduced: 2,
    ministry: [{ portfolio: 'Minister of Food Processing Industries', level: 'cabinet', from_date: '2024-06-10', is_current: true }],
    election_results: [{ year: 2024, votes: 634000, vote_share: 58.7, margin: 231000, runner_up: 'Shiv Chandra Ram', runner_up_party: 'RJD', total_voters: 1540000, turnout: 70.2 }],
    bio: 'Chirag Paswan is NDA ally and Union Food Processing Minister. Son of late Ram Vilas Paswan, he won by a massive 2.3 lakh margin in Hajipur continuing his family\'s stronghold.',
    wikipedia_slug: 'Chirag_Paswan',
    twitter: 'https://twitter.com/iChiragPaswan',
  },

  // ── JHARKHAND (14 seats) ─────────────────────────────────────
  {
    id: 'JH-LOK-001',
    name: 'Champai Soren',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'JH-LOK-SINGHBHUM',
    constituency_name: 'Singhbhum',
    constituency_type: 'parliament',
    state_id: 'JH',
    state_name: 'Jharkhand',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 67,
    gender: 'Male',
    assets: '₹3.8 Crore',
    criminal_cases: 0,
    attendance_percentage: 74,
    questions_asked: 18,
    debates_participated: 12,
    bills_introduced: 1,
    election_results: [{ year: 2024, votes: 398000, vote_share: 44.1, margin: 38000, runner_up: 'Joba Manjhi', runner_up_party: 'JMM', total_voters: 1120000, turnout: 80.5 }],
    bio: 'Champai Soren is a former Chief Minister of Jharkhand who left JMM and joined BJP in 2024. He won the Singhbhum Lok Sabha seat representing tribal interests.',
    wikipedia_slug: 'Champai_Soren',
  },

  // ── ASSAM (14 seats) ─────────────────────────────────────────
  {
    id: 'AS-LOK-001',
    name: 'Gaurav Gogoi',
    party: 'Indian National Congress',
    party_short: 'INC',
    constituency_id: 'AS-LOK-JORHAT',
    constituency_name: 'Jorhat',
    constituency_type: 'parliament',
    state_id: 'AS',
    state_name: 'Assam',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 43,
    gender: 'Male',
    education: 'MA International Relations, American University',
    assets: '₹18.4 Crore',
    criminal_cases: 0,
    attendance_percentage: 86,
    questions_asked: 54,
    debates_participated: 38,
    bills_introduced: 4,
    election_results: [{ year: 2024, votes: 412000, vote_share: 44.2, margin: 48000, runner_up: 'Topon Kumar Gogoi', runner_up_party: 'BJP', total_voters: 1240000, turnout: 75.3 }],
    bio: 'Gaurav Gogoi is Deputy Leader of Congress in Lok Sabha and one of the most active MPs. Son of former Assam CM Tarun Gogoi.',
    wikipedia_slug: 'Gaurav_Gogoi',
    twitter: 'https://twitter.com/GauravGogoiAsm',
  },

  // ── ODISHA (21 seats) ────────────────────────────────────────
  {
    id: 'OD-LOK-001',
    name: 'Dharmendra Pradhan',
    party: 'Bharatiya Janata Party',
    party_short: 'BJP',
    constituency_id: 'OD-LOK-SAMBALPUR',
    constituency_name: 'Sambalpur',
    constituency_type: 'parliament',
    state_id: 'OD',
    state_name: 'Odisha',
    tenure_start: '2024-06-04',
    is_active: true,
    age: 55,
    gender: 'Male',
    education: 'MA',
    assets: '₹4.2 Crore',
    criminal_cases: 0,
    attendance_percentage: 81,
    questions_asked: 22,
    debates_participated: 34,
    bills_introduced: 8,
    ministry: [{ portfolio: 'Minister of Education', level: 'cabinet', from_date: '2021-07-07', is_current: true }],
    election_results: [{ year: 2024, votes: 512000, vote_share: 52.4, margin: 121000, runner_up: 'Pranab Prakash Das', runner_up_party: 'BJD', total_voters: 1280000, turnout: 77.2 }],
    bio: 'Dharmendra Pradhan is Union Education Minister and a key BJP strategist for Odisha. Former Petroleum & Natural Gas Minister who oversaw UJJWALA Yojana.',
    wikipedia_slug: 'Dharmendra_Pradhan',
    twitter: 'https://twitter.com/dpradhanbjp',
  },
];

// ─── Photo resolution via Wikipedia REST API ────────────────────
// No API key needed. Returns thumbnail URL or null.
const _photoCache = new Map<string, string | null>();

export async function fetchRepPhoto(slug: string): Promise<string | null> {
  if (_photoCache.has(slug)) return _photoCache.get(slug)!;
  try {
    const res = await fetch(
      `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(slug)}`,
      { headers: { 'User-Agent': 'ReviewYourLeader/1.0 (https://review-your-leader.vercel.app)' } }
    );
    if (!res.ok) { _photoCache.set(slug, null); return null; }
    const data = await res.json();
    const url = data.thumbnail?.source || data.originalimage?.source || null;
    _photoCache.set(slug, url);
    return url;
  } catch {
    _photoCache.set(slug, null);
    return null;
  }
}

// ─── Lookup helpers ──────────────────────────────────────────────
export function getRepsByState(stateId: string): RepresentativeData[] {
  return REPRESENTATIVES.filter(r => r.state_id === stateId && r.is_active);
}

export function getRepsByConstituency(constituencyId: string): RepresentativeData[] {
  return REPRESENTATIVES.filter(r => r.constituency_id === constituencyId);
}

export function getRepById(id: string): RepresentativeData | undefined {
  return REPRESENTATIVES.find(r => r.id === id);
}

export function searchReps(query: string): RepresentativeData[] {
  const q = query.toLowerCase();
  return REPRESENTATIVES.filter(r =>
    r.name.toLowerCase().includes(q) ||
    r.constituency_name.toLowerCase().includes(q) ||
    r.party.toLowerCase().includes(q) ||
    r.state_name.toLowerCase().includes(q)
  );
}
